version: '3.7'

services:
  database:
    image: postgres
    container_name: database_srag
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=suseds
      - POSTGRES_PASSWORD=head17
      - POSTGRES_DB=srag
    volumes:
      - pgdata:/data/postgres



  app:
    build: .
    container_name: srag
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

      
volumes:
  pgdata:
    driver: local